updates:
  - package-ecosystem: docker-compose
    directories:
      - /compose-json
      - /compose-yaml
    schedule:
      interval: daily
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all
version: 2
